Obligatorio/VozDelEste/WebApplication/Controllers/PatrocinadoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
   public class PatrocinadoresController : Controller
   {
      private VozDelEsteBDEntities db = new VozDelEsteBDEntities();

      // GET: Patrocinadores
      [TienePermiso("Gestion Patrocinadores")]
      public ActionResult Index()
      {
         return View(db.Patrocinador.ToList());
      }

      // GET: Patrocinadores/Details/5
      [TienePermiso("Gestion Patrocinadores")]
      public ActionResult Details(int? id)
      {
         if (id == null)
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

         Patrocinador patrocinador = db.Patrocinador.Find(id);
         if (patrocinador == null)
            return HttpNotFound();

         return View(patrocinador);
      }

      // GET: Patrocinadores/Create
      [TienePermiso("Gestion Patrocinadores")]
      public ActionResult Create()
      {
         return View();
      }

      // POST: Patrocinadores/Create
      [HttpPost]
      [ValidateAntiForgeryToken]
      [TienePermiso("Gestion Patrocinadores")]
      public ActionResult Create(Patrocinador patrocinador, HttpPostedFileBase Imagen)
      {
         if (ModelState.IsValid)
         {
            if (Imagen != null && Imagen.ContentLength > 0)
            {
               var nombreArchivo = Path.GetFileName(Imagen.FileName);
               var rutaRelativa = Path.Combine("~/Assets/Imagenes", nombreArchivo);
               var rutaFisica = Server.MapPath(rutaRelativa);

               Imagen.SaveAs(rutaFisica);
               patrocinador.UrlImagen = Url.Content(rutaRelativa);
            }

            db.Patrocinador.Add(patrocinador);
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         return View(patrocinador);
      }

      // GET: Patrocinadores/Edit/5
      [TienePermiso("Gestion Patrocinadores")]
      public ActionResult Edit(int? id)
      {
         if (id == null)
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

         Patrocinador patrocinador = db.Patrocinador.Find(id);
         if (patrocinador == null)
            return HttpNotFound();

         return View(patrocinador);
      }

      // POST: Patrocinadores/Edit/5
      [HttpPost]
      [ValidateAntiForgeryToken]
      [TienePermiso("Gestion Patrocinadores")]
      public ActionResult Edit(Patrocinador patrocinador, HttpPostedFileBase Imagen)
      {
         if (ModelState.IsValid)
         {
            var patrocinadorDb = db.Patrocinador.Find(patrocinador.Id);
            if (patrocinadorDb == null)
               return HttpNotFound();

            patrocinadorDb.Nombre = patrocinador.Nombre;
            patrocinadorDb.Descripcion = patrocinador.Descripcion;
            patrocinadorDb.TransmisionDiaria = patrocinador.TransmisionDiaria;

            if (Imagen != null && Imagen.ContentLength > 0)
            {
               var nombreArchivo = Path.GetFileName(Imagen.FileName);
               var rutaRelativa = Path.Combine("~/Assets/Imagenes", nombreArchivo);
               var rutaFisica = Server.MapPath(rutaRelativa);

               Imagen.SaveAs(rutaFisica);
               patrocinadorDb.UrlImagen = Url.Content(rutaRelativa);
            }

            db.Entry(patrocinadorDb).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         return View(patrocinador);
      }

      // GET: Patrocinadores/Delete/5
      [TienePermiso("Gestion Patrocinadores")]
      public ActionResult Delete(int? id)
      {
         if (id == null)
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

         Patrocinador patrocinador = db.Patrocinador.Find(id);
         if (patrocinador == null)
            return HttpNotFound();

         return View(patrocinador);
      }

      // POST: Patrocinadores/Delete/5
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      [TienePermiso("Gestion Patrocinadores")]
      public ActionResult DeleteConfirmed(int id)
      {
         Patrocinador patrocinador = db.Patrocinador.Find(id);
         db.Patrocinador.Remove(patrocinador);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing)
            db.Dispose();

         base.Dispose(disposing);
      }
   }
}

Obligatorio/VozDelEste/WebApplication/Views/Patrocinadores/Create.cshtml
@model WebApplication.Models.Patrocinador

@{
   ViewBag.Title = "Create";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
   <link rel="stylesheet" href="~/Content/login.css" />
}
<div class="formulario-container">

   @using (Html.BeginForm())
   {
      @Html.AntiForgeryToken()

      <div class="form-flex">
         <h4>Patrocinador</h4>
         <hr />
         @Html.ValidationSummary(true, "", new { @class = "text-danger" })
         <div class="">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="">
               @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "input-estilo" } })
               @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
         </div>

         <div class="">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="">
               @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "input-estilo" } })
               @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
         </div>

         <div class="">
            @Html.LabelFor(model => model.TransmisionDiaria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="">
               @Html.EditorFor(model => model.TransmisionDiaria, new { htmlAttributes = new { @class = "input-estilo" } })
               @Html.ValidationMessageFor(model => model.TransmisionDiaria, "", new { @class = "text-danger" })
            </div>
         </div>

         <div>
            @Html.Label("Imagen", htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
               <input type="file" name="Imagen" class="input-estilo" />
               @Html.ValidationMessage("Imagen", "", new { @class = "text-danger" })
            </div>
         </div>

         <div class="">
            <div class="">
               <input type="submit" value="Create" class="input-btn" />
            </div>
         </div>
      </div>
      <br />
      <div>
         <a href="@Url.Action("Index")" class="volver">Volver</a>
      </div>
   }


</div>

@section Scripts {
   @Scripts.Render("~/bundles/jquery")
   @Scripts.Render("~/bundles/jqueryval")
}

Obligatorio/VozDelEste/WebApplication/Views/Patrocinadores/Delete.cshtml
@model WebApplication.Models.Patrocinador

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles {
    <link href="~/Content/login.css" rel="stylesheet" />
}

<div class="formulario-container">
    <div class="form-flex">

        <dl>
            <h4>Esta seguro de eliminar esto?</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Descripcion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TransmisionDiaria)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TransmisionDiaria)
                </dd>

                <dd>
                   <img src="@Model.UrlImagen" alt="Imagen del patrocinador" style="width: 70%; margin-bottom: 20px; object-fit:cover; border-radius:5px;" />
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="">
                    <input type="submit" value="Delete" class="input-btn" />
                </div>
                <br />
                @Html.ActionLink("Volver", "Index", null, new { @class = "volver" })
            }
    </div>

</div>

Obligatorio/VozDelEste/WebApplication/Views/Patrocinadores/Details.cshtml
@model WebApplication.Models.Patrocinador

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
    <link href="~/Content/login.css" rel="stylesheet" />
}
<div class="formulario-container">
    <div class="form-flex">
        <h4>@Model.Nombre</h4>
        <hr />
        <dl class="dl-horizontal">
            <dd style="text-align: center">
                <img src="@Model.UrlImagen" alt="Imagen del patrocinador" style="width: 70%; margin-bottom: 20px; object-fit:cover; border-radius:5px;" />
            </dd>
            <dd class="contenido" style="font-size:18px">
                @Html.DisplayFor(model => model.Descripcion)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TransmisionDiaria)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TransmisionDiaria)
            </dd>
            

        </dl>
    </div>
    <p>
        <a href="@Url.Action("Index")" class="volver" style="width:100%; text-align:center;">Volver</a>
    </p>
</div>

Obligatorio/VozDelEste/WebApplication/Views/Patrocinadores/Edit.cshtml
@model WebApplication.Models.Patrocinador

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
    <link href="~/Content/login.css" rel="stylesheet" />
}

<div class="formulario-container">
    @using (Html.BeginForm("Edit", "Patrocinadores", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-flex">
            <h4>Editar Patrocinador</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div>
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "input-estilo" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div>
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.TextAreaFor(model => model.Descripcion, new { @class = "input-estilo", rows = 5 })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div>
                @Html.LabelFor(model => model.TransmisionDiaria, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.TransmisionDiaria, new { htmlAttributes = new { @class = "input-estilo" } })
                    @Html.ValidationMessageFor(model => model.TransmisionDiaria, "", new { @class = "text-danger" })
                </div>
            </div>

            <div>
                @Html.Label("Imagen", htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    <input type="file" name="Imagen" class="input-estilo" />
                    @Html.ValidationMessage("Imagen", "", new { @class = "text-danger" })
                </div>
            </div>

            @* Mostrar imagen actual (opcional) *@
            @if (!string.IsNullOrEmpty(Model.UrlImagen))
            {
                <div style="margin-top:10px;">
                    <label>Imagen actual:</label><br />
                    <img src="@Url.Content(Model.UrlImagen)" alt="Imagen actual" style="max-height: 150px;" />
                </div>
            }

            <div style="margin-top:20px;">
                <input type="submit" value="Guardar" class="input-btn" />
            </div>
        </div>
    }

    <br />
    <div>
        <a href="@Url.Action("Index")" class="volver">Volver</a>
    </div>
</div>

Obligatorio/VozDelEste/WebApplication/Views/Patrocinadores/Index.cshtml
@model IEnumerable<WebApplication.Models.Patrocinador>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
    <link href="~/Content/crudStyle.css" rel="stylesheet" />
}

<p class="btn-container">
    @Html.ActionLink("Crear Patrocinador", "Create", null, new { @class = "btn-create" })
</p>
<table class="tabla-estilo">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransmisionDiaria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </th>
        <th>Opciones</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransmisionDiaria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UrlImagen)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>